#!/bin/bash
DATE=$(date -u +%Y-%m-%d\ %H:%M:%S\ %Z)

## First feed
wget -q -t 5 http://hosts-file.net/ad_servers.asp -O $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts1
sed -i -re '/^#/d ; s/#.*$//' $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts1

## Second feed
wget -q -t 5 "http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext" -O $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts2
sed -re '/^#/d ; s/#.*$//' $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts2 >> $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts1

## Third feed
wget -q -t 5 http://winhelp2002.mvps.org/hosts.txt -O $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts3
sed -re '/^#/d ; s/#.*$//' $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts3 >> $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts1

## Fourth feed
wget -q -t 5 http://www.ismeh.com/HOSTS -O $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts4
sed -re '/^#/d ; s/#.*$//' $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts4 >> $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts1

## Fifth feed
wget -q -t 5 http://someonewhocares.org/hosts/hosts -O $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts5
sed -re '/^#/d ; s/#.*$//' $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts5 >> $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts1

## Clean up
sed -i -e 's/
//g' -e 's/[ \t][ \t]*/ /g' $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts1
sed -i -e 's/^[ \t]*//;s/[ \t]*$//' $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts1
sed -i -re '/\:\:1.*localhost/d' $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts1
sed -i -n -e '/127.0.0.1/p' $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts1
sed -i '/^$/d' $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts1

(cat << EOF) > $ANDROID_BUILD_TOP/vendor/androidx/tools/hosts
##
## File created by Mustaavalkosta's hosts script
##
## Created: $DATE
##
## Sources:
## http://hosts-file.net/ad_servers.asp
## http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
## http://winhelp2002.mvps.org/hosts.txt
## http://www.ismeh.com/HOSTS
## http://someonewhocares.org/hosts/hosts
##

127.0.0.1 localhost
EOF

awk '!seen[$0]++' $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_hosts1 |sort >> $ANDROID_BUILD_TOP/vendor/androidx/tools/hosts

mv $ANDROID_BUILD_TOP/vendor/androidx/tools/hosts $TARGET_HOSTS_FILE
rm $ANDROID_BUILD_TOP/vendor/androidx/tools/temp_*
